import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact page",
    description: "Generated by Sir Shoaib",
  };
  

function RootLayout({children}: any) {

  return (
    <html lang="en">
      <body>
        <h1>Who is Develper?</h1>
        {children}
      </body>
    </html>
  );
  
}

export default RootLayout