import "./globals.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


function RootLayout({children}:any) {
  
  return (

    <html lang="en">
      <body>

      <h1>I am Layout</h1>

      {children}

      <h1>again I am layout</h1>
      
      </body>
    </html>

  )
}

export default RootLayout